apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: crossplane
  namespace: crossplane
spec:
  releaseName: crossplane
  chart:
    spec:
      chart: crossplane
      sourceRef:
        kind: HelmRepository
        name: crossplane
        namespace: flux-system
  interval: 1m0s
  install:
    createNamespace: true
    remediation:
      retries: 3
  values:
    replicas: 3
    extraEnvVarsCrossplane:
      SECRET_USERNAME: "TEST_SECRET"
    env:
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: username
            optional: false 